# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_delate', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['create_date'],
            },
        ),
    ]
