# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
